//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherBrowser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int l {
            get {
                return ((int)(this["l"]));
            }
            set {
                this["l"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int m {
            get {
                return ((int)(this["m"]));
            }
            set {
                this["m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int n {
            get {
                return ((int)(this["n"]));
            }
            set {
                this["n"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string max_min_temp {
            get {
                return ((string)(this["max_min_temp"]));
            }
            set {
                this["max_min_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string max_max_temp {
            get {
                return ((string)(this["max_max_temp"]));
            }
            set {
                this["max_max_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string min_min_temp {
            get {
                return ((string)(this["min_min_temp"]));
            }
            set {
                this["min_min_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string min_max_temp {
            get {
                return ((string)(this["min_max_temp"]));
            }
            set {
                this["min_max_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public string max_wet {
            get {
                return ((string)(this["max_wet"]));
            }
            set {
                this["max_wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string min_wet {
            get {
                return ((string)(this["min_wet"]));
            }
            set {
                this["min_wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string max_rain {
            get {
                return ((string)(this["max_rain"]));
            }
            set {
                this["max_rain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string min_rain {
            get {
                return ((string)(this["min_rain"]));
            }
            set {
                this["min_rain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string max_wind {
            get {
                return ((string)(this["max_wind"]));
            }
            set {
                this["max_wind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string min_wind {
            get {
                return ((string)(this["min_wind"]));
            }
            set {
                this["min_wind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public string max_wash {
            get {
                return ((string)(this["max_wash"]));
            }
            set {
                this["max_wash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string max_ul_vio {
            get {
                return ((string)(this["max_ul_vio"]));
            }
            set {
                this["max_ul_vio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string max_umb {
            get {
                return ((string)(this["max_umb"]));
            }
            set {
                this["max_umb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public string max_star {
            get {
                return ((string)(this["max_star"]));
            }
            set {
                this["max_star"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string min_wash {
            get {
                return ((string)(this["min_wash"]));
            }
            set {
                this["min_wash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string min_ul_vio {
            get {
                return ((string)(this["min_ul_vio"]));
            }
            set {
                this["min_ul_vio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string min_umb {
            get {
                return ((string)(this["min_umb"]));
            }
            set {
                this["min_umb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string min_star {
            get {
                return ((string)(this["min_star"]));
            }
            set {
                this["min_star"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_max_min_temp {
            get {
                return ((bool)(this["bool_max_min_temp"]));
            }
            set {
                this["bool_max_min_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_max_temp {
            get {
                return ((bool)(this["bool_max_max_temp"]));
            }
            set {
                this["bool_max_max_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_min_min_temp {
            get {
                return ((bool)(this["bool_min_min_temp"]));
            }
            set {
                this["bool_min_min_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_max_temp {
            get {
                return ((bool)(this["bool_min_max_temp"]));
            }
            set {
                this["bool_min_max_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_wet {
            get {
                return ((bool)(this["bool_max_wet"]));
            }
            set {
                this["bool_max_wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_wet {
            get {
                return ((bool)(this["bool_min_wet"]));
            }
            set {
                this["bool_min_wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_rain {
            get {
                return ((bool)(this["bool_max_rain"]));
            }
            set {
                this["bool_max_rain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_rain {
            get {
                return ((bool)(this["bool_min_rain"]));
            }
            set {
                this["bool_min_rain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_wind {
            get {
                return ((bool)(this["bool_max_wind"]));
            }
            set {
                this["bool_max_wind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_wind {
            get {
                return ((bool)(this["bool_min_wind"]));
            }
            set {
                this["bool_min_wind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_wash {
            get {
                return ((bool)(this["bool_max_wash"]));
            }
            set {
                this["bool_max_wash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_wash {
            get {
                return ((bool)(this["bool_min_wash"]));
            }
            set {
                this["bool_min_wash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_ult_vio {
            get {
                return ((bool)(this["bool_max_ult_vio"]));
            }
            set {
                this["bool_max_ult_vio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_ult_vio {
            get {
                return ((bool)(this["bool_min_ult_vio"]));
            }
            set {
                this["bool_min_ult_vio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_umb {
            get {
                return ((bool)(this["bool_max_umb"]));
            }
            set {
                this["bool_max_umb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_umb {
            get {
                return ((bool)(this["bool_min_umb"]));
            }
            set {
                this["bool_min_umb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bool_max_star {
            get {
                return ((bool)(this["bool_max_star"]));
            }
            set {
                this["bool_max_star"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_min_star {
            get {
                return ((bool)(this["bool_min_star"]));
            }
            set {
                this["bool_min_star"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_max_min_temp {
            get {
                return ((global::System.Drawing.Color)(this["color_max_min_temp"]));
            }
            set {
                this["color_max_min_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_max_temp {
            get {
                return ((global::System.Drawing.Color)(this["color_max_max_temp"]));
            }
            set {
                this["color_max_max_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_min_temp {
            get {
                return ((global::System.Drawing.Color)(this["color_min_min_temp"]));
            }
            set {
                this["color_min_min_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_min_max_temp {
            get {
                return ((global::System.Drawing.Color)(this["color_min_max_temp"]));
            }
            set {
                this["color_min_max_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_wet {
            get {
                return ((global::System.Drawing.Color)(this["color_max_wet"]));
            }
            set {
                this["color_max_wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_wet {
            get {
                return ((global::System.Drawing.Color)(this["color_min_wet"]));
            }
            set {
                this["color_min_wet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_rain {
            get {
                return ((global::System.Drawing.Color)(this["color_max_rain"]));
            }
            set {
                this["color_max_rain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_rain {
            get {
                return ((global::System.Drawing.Color)(this["color_min_rain"]));
            }
            set {
                this["color_min_rain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_wind {
            get {
                return ((global::System.Drawing.Color)(this["color_max_wind"]));
            }
            set {
                this["color_max_wind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_wind {
            get {
                return ((global::System.Drawing.Color)(this["color_min_wind"]));
            }
            set {
                this["color_min_wind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_wash {
            get {
                return ((global::System.Drawing.Color)(this["color_max_wash"]));
            }
            set {
                this["color_max_wash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_wash {
            get {
                return ((global::System.Drawing.Color)(this["color_min_wash"]));
            }
            set {
                this["color_min_wash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_ul_vio {
            get {
                return ((global::System.Drawing.Color)(this["color_max_ul_vio"]));
            }
            set {
                this["color_max_ul_vio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_ul_vio {
            get {
                return ((global::System.Drawing.Color)(this["color_min_ul_vio"]));
            }
            set {
                this["color_min_ul_vio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_umb {
            get {
                return ((global::System.Drawing.Color)(this["color_max_umb"]));
            }
            set {
                this["color_max_umb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_umb {
            get {
                return ((global::System.Drawing.Color)(this["color_min_umb"]));
            }
            set {
                this["color_min_umb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color color_max_star {
            get {
                return ((global::System.Drawing.Color)(this["color_max_star"]));
            }
            set {
                this["color_max_star"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color color_min_star {
            get {
                return ((global::System.Drawing.Color)(this["color_min_star"]));
            }
            set {
                this["color_min_star"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point MyLocation {
            get {
                return ((global::System.Drawing.Point)(this["MyLocation"]));
            }
            set {
                this["MyLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_url_smallregion {
            get {
                return ((string)(this["back_url_smallregion"]));
            }
            set {
                this["back_url_smallregion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_name {
            get {
                return ((string)(this["back_name"]));
            }
            set {
                this["back_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_l {
            get {
                return ((string)(this["back_l"]));
            }
            set {
                this["back_l"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_m {
            get {
                return ((string)(this["back_m"]));
            }
            set {
                this["back_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_n {
            get {
                return ((string)(this["back_n"]));
            }
            set {
                this["back_n"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_l_name {
            get {
                return ((string)(this["back_l_name"]));
            }
            set {
                this["back_l_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_m_name {
            get {
                return ((string)(this["back_m_name"]));
            }
            set {
                this["back_m_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string back_n_name {
            get {
                return ((string)(this["back_n_name"]));
            }
            set {
                this["back_n_name"] = value;
            }
        }
    }
}
